[versions]
# libraries
junit = "4.13.2"

# plugins
kotlin = "2.0.20"
intelliJPlatform = "2.0.1"
changelog = "2.2.1"
qodana = "2024.1.9"
kover = "0.8.3"
grammarkit = "2022.3.2.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit"}
